# Generated by Django 3.0.4 on 2020-04-26 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemi',
            fields=[
                ('gemi_id', models.AutoField(db_column='Gemi_ID', primary_key=True, serialize=False)),
                ('isim', models.CharField(max_length=20)),
                ('boyut', models.IntegerField(choices=[(50000, 'Handysize (35,000 - 50,000 DWT)'), (60000, 'Supramax (50,000 - 60,000 DWT)'), (80000, 'Panamax (60,000 - 80,000 DWT)')], default=0)),
                ('gemi_kayit_tarih', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Gemi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(blank=True, db_column='Adres', max_length=500, verbose_name='Adres')),
                ('ulke', models.CharField(blank=True, db_column='Ulke', max_length=20, verbose_name='Ülke')),
                ('sehir', models.CharField(blank=True, db_column='Sehir', max_length=20, verbose_name='Şehir')),
                ('firma', models.CharField(blank=True, db_column='Firma Adi', max_length=100, verbose_name='Firma Adı')),
                ('kullanici_kayit_tarih', models.DateTimeField(blank=True, db_column='Kayit Tarihi', default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Kullanici',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sozlesme_onay', models.BooleanField(default=False, verbose_name='Sözleşme Onay')),
            ],
        ),
        migrations.CreateModel(
            name='Yer',
            fields=[
                ('yer_id', models.AutoField(db_column='Yer_ID', primary_key=True, serialize=False)),
                ('tarih', models.DateField(db_column='Tarih')),
                ('kapasite', models.IntegerField(blank=True, default=40000000, null=True)),
            ],
            options={
                'db_table': 'Yer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rezervasyon',
            fields=[
                ('rezervasyon_id', models.AutoField(db_column='Rezervasyon_ID', primary_key=True, serialize=False)),
                ('tarih_giris', models.DateField(db_column='Giris_Tarihi', verbose_name='Giriş Tarihi')),
                ('tarih_cikis', models.DateField(db_column='Cikis_Tarihi', verbose_name='Çıkış Tarihi')),
                ('fiyat', models.IntegerField(default=0)),
                ('gemi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervasyon.Gemi')),
                ('kullanici', models.ForeignKey(db_column='Kullanici_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervasyon.Kullanici')),
            ],
            options={
                'db_table': 'Rezervasyon',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='gemi',
            name='kullanici',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rezervasyon.Kullanici'),
        ),
    ]
